version: '3.0'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
  
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    
    environment:
      - MONGO_URL=mongodb://mongo:27017/PruebaLogin
      - NODE_ENV=development
    
  mongo:
    image: mongo
    volumes:
      - E:/TrabajoDCampo/db:/data/db
    ports:
      - "27017:27017"
  
  cliente:
    build:
      context: ./cliente
      dockerfile: Dockerfile
    image: myapp-cliente
    container_name: myapp-react-cliente
   
    depends_on:
      - server
    ports:
      - "3000:3000"